services:
#    oc_user.example:
#        class: OC\UserBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    oc_user.security:
        class: OC\UserBundle\Security\TokenAuthenticator
